/* Project : Yumo
 * Author : Victory
 * Date : 2021.10.31.
 * Description : Database For Community 'YuMo'
 * Version : 1.0
 * Right : Coon only
 */

/* DROP GEN SQL */
/*
DROP TABLE Y_CODE                    CASCADE CONSTRAINTS;
DROP TABLE Y_USER                    CASCADE CONSTRAINTS;
DROP TABLE Y_BOARD                   CASCADE CONSTRAINTS;
DROP TABLE Y_BOARD_REPLY             CASCADE CONSTRAINTS;
DROP TABLE Y_BOARD_RE_REPLY          CASCADE CONSTRAINTS;
DROP TABLE Y_BOARD_EXTSN             CASCADE CONSTRAINTS;
DROP SEQUENCE Y_USER_SID_SEQ;
DROP SEQUENCE Y_BOARD_SID_SEQ;
DROP SEQUENCE Y_BOARD_REPLY_SID_SEQ;
DROP SEQUENCE Y_BOARD_RE_REPLY_SID_SEQ;
DROP SEQUENCE Y_BOARD_EXTSN_SID_SEQ;
*/

/* DEFINITION TABLES */

/* CODE */
CREATE TABLE Y_CODE
( C_SID       CHAR(20)       NOT NULL
, C_LITERAL   VARCHAR2(32)   DEFAULT '(미등록)'
, C_CODE      CHAR(2)        NOT NULL
, C_KIND      CHAR(2)        NOT NULL
, USE_AT      CHAR(1)        DEFAULT 'Y'  NOT NULL
, REG_DATE    CHAR(14)       DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER    VARCHAR2(36)   DEFAULT 'administrator'
, UPT_DATE    CHAR(14)       DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER    VARCHAR2(36)   DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_CODE           IS '코드';
COMMENT ON COLUMN Y_CODE.C_SID     IS '코드일련번호';
COMMENT ON COLUMN Y_CODE.C_LITERAL IS '코드명칭';
COMMENT ON COLUMN Y_CODE.C_CODE    IS '코드';
COMMENT ON COLUMN Y_CODE.C_KIND    IS '코드종류';
COMMENT ON COLUMN Y_CODE.USE_AT    IS '사용여부';
COMMENT ON COLUMN Y_CODE.REG_DATE  IS '등록일자';
COMMENT ON COLUMN Y_CODE.REG_USER  IS '등록자';
COMMENT ON COLUMN Y_CODE.UPT_DATE  IS '갱신일자';
COMMENT ON COLUMN Y_CODE.UPT_USER  IS '갱신자';

ALTER TABLE Y_CODE ADD CONSTRAINT Y_CODE_PK PRIMARY KEY (C_SID);

CREATE INDEX Y_CODE_IDX_01 ON Y_CODE(C_SID, C_CODE);

CREATE INDEX Y_CODE_IDX_02 ON Y_CODE(C_CODE, C_KIND);

CREATE INDEX Y_CODE_IDX_03 ON Y_CODE(C_SID, C_CODE, C_KIND);


/* USER */
CREATE SEQUENCE Y_USER_SID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 99999999
CYCLE;

CREATE TABLE Y_USER
( USER_SID              CHAR(20)                     NOT NULL
, USER_ID               VARCHAR2(36)                 NOT NULL
, USER_PW               VARCHAR2(128)                NOT NULL
, USER_NAME             VARCHAR2(64)                 NOT NULL
, USER_NICK             VARCHAR2(64)                 NOT NULL
, USER_PHONE            CHAR(11)                     NOT NULL
, USER_BIRTH            CHAR(8)                      NOT NULL
, USER_EMAIL_ID         VARCHAR2(64)
, USER_EMAIL_PF         VARCHAR2(32)
, USER_GENDER           CHAR(1)                      NOT NULL
, USER_GRADE            CHAR(2)        DEFAULT '01'
, USER_LOGIN_FAIL_CNT   NUMBER(19,0)   DEFAULT 0     NOT NULL
, USER_LOGIN_BLOCK_AT   CHAR(1)        DEFAULT 'N'   NOT NULL
, USER_LAST_LOGIN_DATE  CHAR(14)
, USE_AT                CHAR(1)        DEFAULT 'Y'   NOT NULL
, REG_DATE              CHAR(14)       DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER              VARCHAR2(36)   DEFAULT 'administrator'
, UPT_DATE              CHAR(14)       DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER              VARCHAR2(36)   DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_USER                      IS '회원';
COMMENT ON COLUMN Y_USER.USER_SID             IS '회원일련번호';
COMMENT ON COLUMN Y_USER.USER_ID              IS '회원ID';
COMMENT ON COLUMN Y_USER.USER_PW              IS '회원비밀번호';
COMMENT ON COLUMN Y_USER.USER_NAME            IS '회원명';
COMMENT ON COLUMN Y_USER.USER_NICK            IS '회원닉네임';
COMMENT ON COLUMN Y_USER.USER_PHONE           IS '회원휴대폰번호';
COMMENT ON COLUMN Y_USER.USER_BIRTH           IS '회원생년월일';
COMMENT ON COLUMN Y_USER.USER_EMAIL_ID        IS '회월이메일ID';
COMMENT ON COLUMN Y_USER.USER_EMAIL_PF        IS '회원이메일도메인';
COMMENT ON COLUMN Y_USER.USER_GENDER          IS '회원성별';
COMMENT ON COLUMN Y_USER.USER_GRADE           IS '회원등급';
COMMENT ON COLUMN Y_USER.USER_LOGIN_FAIL_CNT  IS '로그인실패횟수';
COMMENT ON COLUMN Y_USER.USER_LOGIN_BLOCK_AT  IS '로그인중지여부';
COMMENT ON COLUMN Y_USER.USER_LAST_LOGIN_DATE IS '최종로그인일자';
COMMENT ON COLUMN Y_USER.USE_AT               IS '사용여부';
COMMENT ON COLUMN Y_USER.REG_DATE             IS '등록일자';
COMMENT ON COLUMN Y_USER.REG_USER             IS '등록자';
COMMENT ON COLUMN Y_USER.UPT_DATE             IS '갱신일자';
COMMENT ON COLUMN Y_USER.UPT_USER             IS '갱신자';

ALTER TABLE Y_USER ADD CONSTRAINT Y_USER_PK PRIMARY KEY (USER_SID);

CREATE INDEX Y_USER_IDX_01 ON Y_USER(USER_ID);

CREATE INDEX Y_USER_IDX_02 ON Y_USER(USER_ID, USER_PW);

CREATE INDEX Y_USER_IDX_03 ON Y_USER(USER_NAME, USER_BIRTH);

CREATE INDEX Y_USER_IDX_04 ON Y_USER(USER_NAME, USER_PHONE);

CREATE INDEX Y_USER_IDX_05 ON Y_USER(USER_NAME, USER_PHONE, USER_BIRTH);

CREATE INDEX Y_USER_IDX_06 ON Y_USER(USER_EMAIL_ID, USER_EMAIL_PF);


/* BOARD */
CREATE SEQUENCE Y_BOARD_SID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 99999999
CYCLE;

CREATE TABLE Y_BOARD
( BOARD_SID         CHAR(24)                    NOT NULL
, BOARD_TITLE       VARCHAR2(128)               NOT NULL
, BOARD_CONTENT     VARCHAR2(4000)  DEFAULT '(About Blank)'
, BOARD_KIND_CODE   CHAR(2)                     NOT NULL
, BOARD_TOP_VIEW_AT CHAR(1)         DEFAULT 'N' NOT NULL
, BOARD_LIKE_CNT    NUMBER(19,0)    DEFAULT 0   NOT NULL
, BOARD_HATE_CNT    NUMBER(19,0)    DEFAULT 0   NOT NULL
, BOARD_VIEW_CNT    NUMBER(19,0)    DEFAULT 0   NOT NULL
, DEL_YN            CHAR(1)         DEFAULT 'N' NOT NULL
, REG_DATE          CHAR(14)        DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER          VARCHAR2(36)    DEFAULT 'administrator'
, UPT_DATE          CHAR(14)        DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER          VARCHAR2(36)    DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_BOARD                   IS '게시판';
COMMENT ON COLUMN Y_BOARD.BOARD_SID         IS '게시판일련번호';
COMMENT ON COLUMN Y_BOARD.BOARD_TITLE       IS '게시판제목';
COMMENT ON COLUMN Y_BOARD.BOARD_CONTENT     IS '게시판내용';
COMMENT ON COLUMN Y_BOARD.BOARD_KIND_CODE   IS '게시판종류코드';
COMMENT ON COLUMN Y_BOARD.BOARD_TOP_VIEW_AT IS '게시판상단고정여부';
COMMENT ON COLUMN Y_BOARD.BOARD_LIKE_CNT    IS '좋아요횟수';
COMMENT ON COLUMN Y_BOARD.BOARD_HATE_CNT    IS '싫어요횟수';
COMMENT ON COLUMN Y_BOARD.BOARD_VIEW_CNT    IS '조회수';
COMMENT ON COLUMN Y_BOARD.DEL_YN            IS '삭제여부';
COMMENT ON COLUMN Y_BOARD.REG_DATE          IS '등록일자';
COMMENT ON COLUMN Y_BOARD.REG_USER          IS '등록자';
COMMENT ON COLUMN Y_BOARD.UPT_DATE          IS '갱신일자';
COMMENT ON COLUMN Y_BOARD.UPT_USER          IS '갱신자';

ALTER TABLE Y_BOARD ADD CONSTRAINT Y_BOARD_PK PRIMARY KEY (BOARD_SID);

CREATE INDEX Y_BOARD_IDX_01 ON Y_BOARD(REG_USER);

CREATE INDEX Y_BOARD_IDX_02 ON Y_BOARD(BOARD_TITLE);

CREATE INDEX Y_BOARD_IDX_03 ON Y_BOARD(BOARD_TITLE, BOARD_CONTENT);


CREATE SEQUENCE Y_BOARD_REPLY_SID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 99999999
CYCLE;

CREATE TABLE Y_BOARD_REPLY
( BOARD_REPLY_SID       CHAR(24)                    NOT NULL
, BOARD_SID             CHAR(24)                    NOT NULL
, BOARD_REPLY_CONTENT   VARCHAR2(512)               NOT NULL
, BOARD_REPLY_LIKE_CNT  NUMBER(19,0)  DEFAULT 0
, BOARD_REPLY_HATE_CNT  NUMBER(19,0)  DEFAULT 0
, DEL_YN                CHAR(1)       DEFAULT 'N'
, REG_DATE              CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER              VARCHAR2(36)  DEFAULT 'administrator'
, UPT_DATE              CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER              VARCHAR2(36)  DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_BOARD_REPLY                      IS '게시판댓글';
COMMENT ON COLUMN Y_BOARD_REPLY.BOARD_REPLY_SID      IS '게시판댓글일련번호';
COMMENT ON COLUMN Y_BOARD_REPLY.BOARD_SID            IS '게시판일련번호';
COMMENT ON COLUMN Y_BOARD_REPLY.BOARD_REPLY_CONTENT  IS '게시판댓글내용';
COMMENT ON COLUMN Y_BOARD_REPLY.BOARD_REPLY_LIKE_CNT IS '댓글좋아요횟수';
COMMENT ON COLUMN Y_BOARD_REPLY.BOARD_REPLY_HATE_CNT IS '댓글싫어요횟수';
COMMENT ON COLUMN Y_BOARD_REPLY.DEL_YN               IS '삭제여부';
COMMENT ON COLUMN Y_BOARD_REPLY.REG_DATE             IS '등록일자';
COMMENT ON COLUMN Y_BOARD_REPLY.REG_USER             IS '등록자';
COMMENT ON COLUMN Y_BOARD_REPLY.UPT_DATE             IS '갱신일자';
COMMENT ON COLUMN Y_BOARD_REPLY.UPT_USER             IS '갱신자';

ALTER TABLE Y_BOARD_REPLY ADD CONSTRAINT Y_BOARD_REPLY_PK PRIMARY KEY (BOARD_REPLY_SID, BOARD_SID);

CREATE INDEX Y_BOARD_REPLY_IDX_01 ON Y_BOARD_REPLY(BOARD_REPLY_CONTENT);

CREATE INDEX Y_BOARD_REPLY_IDX_02 ON Y_BOARD_REPLY(REG_USER);


CREATE SEQUENCE Y_BOARD_RE_REPLY_SID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 99999999
CYCLE;

CREATE TABLE Y_BOARD_RE_REPLY
( BOARD_RE_REPLY_SID      CHAR(24)                    NOT NULL
, BOARD_REPLY_SID         CHAR(24)                    NOT NULL
, BOARD_SID               CHAR(24)                    NOT NULL
, BOARD_RE_REPLY_CONTENT  VARCHAR2(512)               NOT NULL
, BOARD_RE_REPLY_LIKE_CNT NUMBER(19,0)  DEFAULT 0
, BOARD_RE_REPLY_HATE_CNT NUMBER(19,0)  DEFAULT 0
, DEL_YN                  CHAR(1)       DEFAULT 'N'
, REG_DATE                CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER                VARCHAR2(36)  DEFAULT 'administrator'
, UPT_DATE                CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER                VARCHAR2(36)  DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_BOARD_RE_REPLY                         IS '게시판대댓글';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_RE_REPLY_SID      IS '게시판대댓글일련번호';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_REPLY_SID         IS '게시판댓글일련번호';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_SID               IS '게시판일련번호';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_RE_REPLY_CONTENT  IS '게시판댓글내용';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_RE_REPLY_LIKE_CNT IS '대댓글좋아요횟수';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.BOARD_RE_REPLY_HATE_CNT IS '대댓글싫어요횟수';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.DEL_YN                  IS '삭제여부';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.REG_DATE                IS '등록일자';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.REG_USER                IS '등록자';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.UPT_DATE                IS '갱신일자';
COMMENT ON COLUMN Y_BOARD_RE_REPLY.UPT_USER                IS '갱신자';

ALTER TABLE Y_BOARD_RE_REPLY ADD CONSTRAINT Y_BOARD_RE_REPLY_PK PRIMARY KEY (BOARD_RE_REPLY_SID, BOARD_REPLY_SID, BOARD_SID);

CREATE INDEX Y_BOARD_RE_REPLY_IDX_01 ON Y_BOARD_RE_REPLY(BOARD_RE_REPLY_CONTENT);

CREATE INDEX Y_BOARD_RE_REPLY_IDX_02 ON Y_BOARD_RE_REPLY(REG_USER);


CREATE SEQUENCE Y_BOARD_EXTSN_SID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999999
CYCLE;

CREATE TABLE Y_BOARD_EXTSN
( BOARD_EXTSN_SID                           CHAR(24)                    NOT NULL
, BOARD_SID                                 CHAR(24)                    NOT NULL
, BOARD_EXTSN_DIRECTORY_ROUTE               VARCHAR2(256)               NOT NULL
, BOARD_EXTSN_FILE_NAME                     VARCHAR2(64)                NOT NULL
, BOARD_EXTSN_FILE_EXTENSION                VARCHAR2(8)                 NOT NULL
, BOARD_EXTSN_FILE_EXTENSION_CD             CHAR(2)                     NOT NULL
, THUMB_AT                                  CHAR(1)       DEFAULT 'N'
, USE_AT                                    CHAR(1)       DEFAULT 'Y'
, REG_DATE                                  CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, REG_USER                                  VARCHAR2(36)  DEFAULT 'administrator'
, UPT_DATE                                  CHAR(14)      DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')
, UPT_USER                                  VARCHAR2(36)  DEFAULT 'administrator'
);

COMMENT ON TABLE  Y_BOARD_EXTSN                                           IS '게시판컨텐츠';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_EXTSN_SID                           IS '게시판컨텐츠일련번호';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_SID                                 IS '게시판일련번호';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_EXTSN_DIRECTORY_ROUTE               IS '컨텐츠경로';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_EXTSN_FILE_NAME                     IS '컨텐츠명';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_EXTSN_FILE_EXTENSION                IS '확장자명';
COMMENT ON COLUMN Y_BOARD_EXTSN.BOARD_EXTSN_FILE_EXTENSION_CD             IS '확장자코드';
COMMENT ON COLUMN Y_BOARD_EXTSN.THUMB_AT                                  IS '썸네일여부';
COMMENT ON COLUMN Y_BOARD_EXTSN.USE_AT                                    IS '사용여부';
COMMENT ON COLUMN Y_BOARD_EXTSN.REG_DATE                                  IS '등록일자';
COMMENT ON COLUMN Y_BOARD_EXTSN.REG_USER                                  IS '등록자';
COMMENT ON COLUMN Y_BOARD_EXTSN.UPT_DATE                                  IS '갱신일자';
COMMENT ON COLUMN Y_BOARD_EXTSN.UPT_USER                                  IS '갱신자';

ALTER TABLE Y_BOARD_EXTSN ADD CONSTRAINT Y_BOARD_EXTSN_PK PRIMARY KEY (BOARD_EXTSN_SID, BOARD_SID);

CREATE INDEX Y_BOARD_EXTSN_IDX_01 ON Y_BOARD_EXTSN(BOARD_SID);

CREATE INDEX Y_BOARD_EXTSN_IDX_02 ON Y_BOARD_EXTSN(BOARD_EXTSN_FILE_NAME);

CREATE INDEX Y_BOARD_EXTSN_IDX_03 ON Y_BOARD_EXTSN(REG_USER);

INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('1',6,'0'),'관리','00','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('2',6,'0'),'새싹','02','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('3',6,'0'),'눈팅','03','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('4',6,'0'),'관심','04','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('5',6,'0'),'열심','05','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('6',6,'0'),'헌신','06','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('7',6,'0'),'장이','07','01');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('8',6,'0'),'꾼' ,'08','01');

INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('9',6,'0'),'공지사항' ,'01','02');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('10',6,'0'),'자유게시판' ,'02','02');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('11',6,'0'),'익명게시판' ,'03','02');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('12',6,'0'),'FAQ' ,'04','02');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('13',6,'0'),'고객센터' ,'04','02');

INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('14',6,'0'),'jpg' ,'01','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('15',6,'0'),'jpeg' ,'02','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('16',6,'0'),'bmp' ,'03','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('17',6,'0'),'png' ,'04','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('18',6,'0'),'gif' ,'05','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('19',6,'0'),'svg' ,'06','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('20',6,'0'),'mp4' ,'07','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('21',6,'0'),'mov' ,'08','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('22',6,'0'),'wmv' ,'09','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('23',6,'0'),'avi' ,'10','03');
INSERT INTO Y_CODE(C_SID,C_LITERAL,C_CODE,C_KIND)VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS')||LPAD('24',6,'0'),'mkv' ,'11','03');

COMMIT;